version: '3.6'

services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: nitharios/phoenix-server
    container_name: goserver
    restart: unless-stopped
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "80:80"
      # - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      # - dhparam:/etc/ssl/certs
      - ./config:/etc/nginx/conf.d
      # - ./logs/nginx:/var/log/nginx
    depends_on:
      - goserver
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email n.niosco@gmail.com --agree-tos --no-eff-email --staging -d api.zephyrbyte.com
  
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/nitharios/golang/src/github.com/nitharios/phoenix/
      o: bind
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/nitharios/golang/src/github.com/nitharios/phoenix/dhparam/
  #     o: bind

networks:
  app-network:
    driver: bridge